# Generated by Django 2.1.5 on 2020-04-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20200412_2306'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Program'),
            preserve_default=False,
        ),
    ]
