# Generated by Django 2.1.5 on 2020-04-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_screen_no_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='column',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='row',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
