# Generated by Django 2.1.5 on 2020-04-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20200403_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='column',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='row',
        ),
        migrations.AddField(
            model_name='screen',
            name='no_cols',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='no_rows',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
