# Generated by Django 2.1.5 on 2020-04-04 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20200403_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='day',
            field=models.DateField(default=datetime.date(2020, 4, 4)),
        ),
        migrations.AlterField(
            model_name='program',
            name='hour',
            field=models.TimeField(default=datetime.time(14, 1, 59, 235342)),
        ),
    ]
