# Generated by Django 2.1.5 on 2020-04-04 14:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200404_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='program',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
