# Generated by Django 2.1.5 on 2020-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20200404_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=1, default=8.9, max_digits=3),
            preserve_default=False,
        ),
    ]
