# Generated by Django 2.1.5 on 2020-04-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20200406_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='seating_pattern',
            field=models.CharField(choices=[('SEAT_1', 'SEAT_1')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
