# Generated by Django 2.1.5 on 2020-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_screen_seating_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='position',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable')], max_length=20),
        ),
    ]
