# Generated by Django 2.1.5 on 2020-04-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20200412_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
    ]
