# Generated by Django 2.1.5 on 2020-04-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_remove_seat_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Available'), ('2', 'Reserved'), ('3', 'Unavailable')], max_length=20)),
                ('position', models.CharField(max_length=6)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Show')),
            ],
            options={
                'verbose_name_plural': 'ShowSeat',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ManyToManyField(through='movies.ShowSeat', to='movies.Show'),
        ),
    ]
